name: bolt-deployment
dependencies:
  - python == 3.5.2
  - libffi == 3.2.1
  - flask == 0.11.1
  - nltk == 3.2.1
  - spacy == 0.101.0
  - scikit-learn=0.17.1=np111py35_nomkl_2
  - psycopg2 == 2.6.2
  - nomkl == 1.0
  - pip:
    - cachetools == 1.1.6
    - flask-restful == 0.3.5
    - python-dotenv == 0.5.1
    - textacy == 0.3.0
    