name: bolt-deployment
dependencies:
  - python == 3.5.2
  - flask == 0.11.1
  - nltk == 3.2.1
  - numpy == 1.11.0
  - spacy == 0.101.0
  - utils == 0.12
  - scikit_learn == 0.17.1
  - psycopg2 == 2.6.2
  - pip:
    - cachetools == 1.1.6
    - textacy == 0.2.2
    - flask-restful == 0.3.5
    - logging == 0.4.9.6