branch-defaults:
  cmuell89-pyDuckling:
    environment: bolt-green
  default:
    environment: bolt-2
  elastic-beanstalk:
    environment: bolt-2
environment-defaults:
  bolt-green:
    branch: null
    repository: null
global:
  application_name: Bolt
  default_ec2_keyname: aws-eb
  default_platform: 64bit Amazon Linux 2016.03 v2.1.6 running Python 3.4
  default_region: us-west-2
  profile: eb-cli
  sc: git
